services:
  app:
    image: kochev2t/devops-for-programmers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app:/app
    command: make test
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
