services:
  app:
    image: kochev2t/devops-for-programmers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app:/app
    command: make test
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
